# Generated by Django 4.1.5 on 2023-01-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_website', '0003_product_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shopping_website/images'),
        ),
    ]
