# Generated by Django 4.1.5 on 2023-02-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_website', '0005_alter_product_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
