# Generated by Django 4.1.5 on 2023-02-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_website', '0007_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
